import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { Avatar, Style } from '@dicebear/core';
import definition from '@dicebear/styles/avataaars.json' with { type: 'json' };

const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, '../../assets/avatars');

// Feature choices are explicit so a dependency update cannot introduce an
// unfriendly expression. Backgrounds mirror AvatarPickerScreen's brand-token
// sequence, allowing the whole portrait circle to become greyscale when it is
// not selected.
const presets = [
  {
    seed: 'alder',
    skinColor: '#614335',
    topVariant: 'fro',
    hairColor: '#2c1b18',
    eyesVariant: 'happy',
    eyebrowsVariant: 'defaultNatural',
    clothesVariant: 'hoodie',
    clothesColor: '#65c9ff',
    backgroundColor: '#ffe6ab',
  },
  {
    seed: 'brook',
    skinColor: '#ae5d29',
    topVariant: 'hijab',
    hatColor: '#25557c',
    eyesVariant: 'default',
    eyebrowsVariant: 'default',
    clothesVariant: 'collarAndSweater',
    clothesColor: '#ff5c5c',
    backgroundColor: '#a9e0e4',
  },
  {
    seed: 'coral',
    skinColor: '#d08b5b',
    topVariant: 'turban',
    hatColor: '#3c4f5c',
    eyesVariant: 'happy',
    eyebrowsVariant: 'raisedExcitedNatural',
    facialHairVariant: 'beardLight',
    facialHairColor: '#4a312c',
    facialHairProbability: 100,
    clothesVariant: 'shirtVNeck',
    clothesColor: '#a7ffc4',
    backgroundColor: '#ffe8dc',
  },
  {
    seed: 'delta',
    skinColor: '#ffdbb4',
    topVariant: 'curly',
    hairColor: '#4a312c',
    eyesVariant: 'happy',
    eyebrowsVariant: 'raisedExcited',
    accessoriesVariant: 'round',
    accessoriesColor: '#262e33',
    accessoriesProbability: 100,
    clothesVariant: 'hoodie',
    clothesColor: '#ffafb9',
    backgroundColor: '#ddebdc',
  },
  {
    seed: 'estuary',
    skinColor: '#ae5d29',
    topVariant: 'dreads02',
    hairColor: '#2c1b18',
    eyesVariant: 'default',
    eyebrowsVariant: 'defaultNatural',
    facialHairVariant: 'beardMedium',
    facialHairColor: '#2c1b18',
    facialHairProbability: 100,
    clothesVariant: 'overall',
    clothesColor: '#a7ffc4',
    backgroundColor: '#f5b69b',
  },
  {
    seed: 'fern',
    skinColor: '#edb98a',
    topVariant: 'bob',
    hairColor: '#c93305',
    eyesVariant: 'happy',
    eyebrowsVariant: 'raisedExcitedNatural',
    accessoriesVariant: 'prescription01',
    accessoriesColor: '#3c4f5c',
    accessoriesProbability: 100,
    clothesVariant: 'shirtScoopNeck',
    clothesColor: '#ffffb1',
    backgroundColor: '#e9f7f7',
  },
  {
    seed: 'grove',
    skinColor: '#614335',
    topVariant: 'shavedSides',
    hairColor: '#2c1b18',
    eyesVariant: 'default',
    eyebrowsVariant: 'flatNatural',
    facialHairVariant: 'moustacheFancy',
    facialHairColor: '#2c1b18',
    facialHairProbability: 100,
    clothesVariant: 'blazerAndShirt',
    clothesColor: '#5199e4',
    backgroundColor: '#ffe6ab',
  },
  {
    seed: 'harbour',
    skinColor: '#ffdbb4',
    topVariant: 'bun',
    hairColor: '#d6b370',
    eyesVariant: 'default',
    eyebrowsVariant: 'default',
    accessoriesVariant: 'round',
    accessoriesColor: '#25557c',
    accessoriesProbability: 100,
    clothesVariant: 'overall',
    clothesColor: '#ff488e',
    backgroundColor: '#a9e0e4',
  },
  {
    seed: 'iris',
    skinColor: '#ae5d29',
    topVariant: 'froBand',
    hairColor: '#724133',
    hatColor: '#ff5c5c',
    eyesVariant: 'happy',
    eyebrowsVariant: 'raisedExcitedNatural',
    clothesVariant: 'shirtCrewNeck',
    clothesColor: '#65c9ff',
    backgroundColor: '#ffe8dc',
  },
  {
    seed: 'juniper',
    skinColor: '#edb98a',
    topVariant: 'winterHat02',
    hatColor: '#25557c',
    eyesVariant: 'default',
    eyebrowsVariant: 'defaultNatural',
    accessoriesVariant: 'prescription02',
    accessoriesColor: '#262e33',
    accessoriesProbability: 100,
    clothesVariant: 'hoodie',
    clothesColor: '#3c4f5c',
    backgroundColor: '#ddebdc',
  },
  {
    seed: 'kelp',
    skinColor: '#edb98a',
    topVariant: 'straightAndStrand',
    hairColor: '#2c1b18',
    eyesVariant: 'happy',
    eyebrowsVariant: 'raisedExcited',
    clothesVariant: 'blazerAndSweater',
    clothesColor: '#ffafb9',
    backgroundColor: '#f5b69b',
  },
  {
    seed: 'lagoon',
    skinColor: '#d08b5b',
    topVariant: 'shortCurly',
    hairColor: '#a55728',
    eyesVariant: 'default',
    eyebrowsVariant: 'defaultNatural',
    facialHairVariant: 'beardLight',
    facialHairColor: '#a55728',
    facialHairProbability: 100,
    accessoriesVariant: 'prescription02',
    accessoriesColor: '#3c4f5c',
    accessoriesProbability: 100,
    clothesVariant: 'graphicShirt',
    clothesColor: '#ff5c5c',
    clothesGraphicVariant: 'bear',
    backgroundColor: '#e9f7f7',
  },
];

await mkdir(output, { recursive: true });
const style = new Style(definition);
for (const [index, preset] of presets.entries()) {
  const avatar = new Avatar(style, {
    ...preset,
    mouthVariant: 'smile',
    facialHairProbability: preset.facialHairProbability ?? 0,
    accessoriesProbability: preset.accessoriesProbability ?? 0,
    borderRadius: [50],
  });
  const filename = `avatar-${String(index + 1).padStart(2, '0')}.svg`;
  await writeFile(resolve(output, filename), avatar.toString(), 'utf8');
}
